const routes = {
    home: "/",
    danh_muc_giao_vien: "/quan-ly-danh-muc/danh-muc-giao-vien",
    them_giao_vien: "/quan-ly-danh-muc/them-giao-vien",
    danh_muc_thiet_bi: "/quan-ly-danh-muc/danh-muc-thiet-bi",
    them_thiet_bi: "/quan-ly-danh-muc/them-thiet-bi",
    danh_muc_kho_phong: "/quan-ly-danh-muc/danh-muc-kho-phong",
    update_giao_vien: "/quan-ly-danh-muc/update-giao-vien",
    update_thiet_bi: "/quan-ly-danh-muc/update-thiet-bi",
    danh_sach_thiet_bi: "/quan-ly-thiet-bi/danh-sach-thiet-bi",
    chon_thiet_bi_khai_bao: "/quan-ly-thiet-bi/chon-thiet-bi-khai-bao",
    khai_bao_thiet_bi: "/quan-ly-thiet-bi/khai-bao-thiet-bi",
    ghi_giam: "/quan-ly-thiet-bi/ghi-giam",
    ghi_tang: "/quan-ly-thiet-bi/ghi-tang",
    tang_thiet_bi: "/quan-ly-thiet-bi/tang-thiet-bi",
    thanh_ly_thiet_bi: "/quan-ly-thiet-bi/thanh-ly-thiet-bi",
    khai_bao_hong_mat: "/quan-ly-thiet-bi/khai-bao-hong-mat",
    theo_doi_hong_mat: "/quan-ly-thiet-bi/theo-doi-hong-mat",
    them_phieu_muon: "/quan-ly-muon-tra/them-phieu-muon",
    them_phieu_tra: "/quan-ly-muon-tra/ghi-tra",
    muon_tra_thiet_bi: "/quan-ly-muon-tra/muon-tra-thiet-bi",
    lich_su_tra: "/quan-ly-muon-tra/lich-su-tra",
    update_ghi_giam: "/quan-ly-thiet-bi/update-ghi-giam",
    duyet_tang_tb: "/quan-ly-thiet-bi/duyet-tang-tb",
    login: "/login",
    bao_cao_thong_ke: "/bao-cao-thong-ke",
    update_hong_mat: "/quan-ly-thiet-bi/update-hong-mat",
    update_phieu_muon: "/quan-ly-muon-tra/update-phieu-muon"
};

export default routes;
